---
- name: Install KDE packages
  become: yes
  package:
    name: "{{ kde_packages }}"
  tags:
    - kde

- name: Install sddm
  become: yes
  package:
    name: sddm
  tags:
    - kde

- name: Disable any pre-existing display-manager
  become: yes
  file:
    src: /usr/lib/systemd/system/sddm.service
    dest: /etc/systemd/system/display-manager.service
    state: link
  tags:
    - kde

- name: Enable sddm
  become: yes
  service:
    name: sddm
    state: started
  tags:
    - kde
