---
- name: Setup user-level changes
  hosts: localhost
  tasks:
    - include_tasks:
        file: user_tasks.yaml
        apply:
          vars:
            user: "{{ ansible_user }}"
            user_details: "{{ workstation_users[ansible_user] }}"
