- name: Setup networking
  hosts: localhost
  gather_facts: no
  roles:
    - wifi-client

- name: Wait for networking
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for network connectivity
      wait_for:
        path: /etc/resolv.conf
        search_regex: ^nameserver
      tags:
        - wait

- name: Make system-level changes
  hosts: localhost
  roles:
    - luks
    - kde
    - workstation
    - openvpn

- name: Setup user-level changes
  hosts: localhost
  tasks:
    - include_tasks:
        file: user_tasks.yaml
        apply:
          become: yes
          become_user: "{{ workstation_user.key }}"
          vars:
            user: "{{ workstation_user.key }}"
            user_details: "{{ workstation_user.value }}"
      loop: "{{ workstation_users | dict2items }}"
      loop_control:
        loop_var: workstation_user
      tags:
        - workstation_user
