---
- name: Create autostart directory
  file:
    dest: "{{ ansible_user_dir }}/.config/autostart"
    state: directory
  tags:
    - kde

- name: Make yakuake autostart
  file:
    src: /usr/share/applications/org.kde.yakuake.desktop
    dest: "{{ ansible_user_dir }}/.config/autostart/org.kde.yakuake.desktop"
    state: link
  tags:
    - kde

- name: Configure yakuake
  copy:
    src: yakuakerc
    dest: "{{ ansible_user_dir }}/.config/yakuakerc"
  tags:
    - kde

- name: Copy plasma config script
  copy:
    src: configure_plasma.sh
    dest: "{{ ansible_user_dir }}/.config/autostart-scripts/configure_plasma.sh"
    mode: 0744
  tags:
    - kde
    - plasma

- name: Copy plasma config javascript
  template:
    src: kde_menu_config.js.j2
    dest: "{{ ansible_user_dir }}/.config/kde_menu_config.js"
  tags:
    - kde
    - plasma

- name: Configure menus (if running)
  command: "{{ ansible_user_dir }}/.config/autostart-scripts/configure_plasma.sh"
  tags:
    - kde
    - plasma
