- name: Checkout dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ user }}/dotfiles"
    version: master
  tags:
    - dotfiles

- name: Install dotfiles symlinks
  script: install_dotfiles.py /home/{{ user }}/dotfiles /home/{{ user }}
  tags:
    - dotfiles
