- name: Checkout dotfiles
  become: yes
  become_user: "{{ workstation_user }}"
  git:
    repo: "{{ workstation_dotfiles_repo }}"
    dest: /home/{{ workstation_user }}/dotfiles
  tags:
    - dotfiles

- name: Install dotfiles symlinks
  become: yes
  become_user: "{{ workstation_user }}"
  script: install_dotfiles.py /home/{{ workstation_user }}/dotfiles /home/{{ workstation_user }}
