---
- name: Add rpmfusion repos
  become: yes
  package:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  when: workstation_enable_rpmfusion

- name: Add VS Code repo key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VS Code repo
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode

- name: Update installed packages
  become: yes
  package:
    name: "*"
    state: latest

- name: Install packages
  become: yes
  package:
    name: "{{ workstation_packages }}"

- name: Enable classic snap support
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: workstation_use_snapd

- name: Install snaps
  become: yes
  snap:
    name: "{{ workstation_snaps }}"
  when: workstation_use_snapd

- name: Install snaps (classic)
  become: yes
  snap:
    name: "{{ item }}"
    classic: yes
  with_items: "{{ workstation_snaps_classic }}"
  when: workstation_use_snapd

- name: Create an admin user, append to wheel group
  become: yes
  user:
    name: "{{ workstation_user }}"
    groups: wheel
    append: yes
