---
- name: Install VirtualBox
  become: yes
  package:
    name:
      - akmod-VirtualBox
      - kernel-devel
      - kernel-devel-{{ ansible_kernel }}
      - VirtualBox
  tags:
    - virtualbox

- name: Build VirtualBox kernel modules via akmods
  become: yes
  command: akmods
  tags:
    - virtualbox

- name: Load VirtualBox kernel modules
  become: yes
  service:
    name: systemd-modules-load
    state: restarted
  tags:
    - virtualbox

- name: Add workstation user to vboxusers group
  become: yes
  user:
    name: "{{ workstation_user }}"
    groups: vboxusers
    append: yes
  tags:
    - virtualbox
